### ISSUE TITLE
`FLT_EVAL_METHOD` and `LDBL_EPSILON`

### ISSUE THREAD

**Issue by colluca** [kraj/musl#3]
The `arch/riscv64/bits/float.h` file defines: https://github.com/kraj/musl/blob/a6c49977772a200216bd3a63b490d467663384b6/arch/riscv64/bits/float.h#L1
And:
https://github.com/kraj/musl/blob/a6c49977772a200216bd3a63b490d467663384b6/arch/riscv64/bits/float.h#L6

It does not define `DBL_EPSILON`, which is however used in `src/math/ceil.c` when `FLT_EVAL_METHOD` is 0:
https://github.com/kraj/musl/blob/a6c49977772a200216bd3a63b490d467663384b6/src/math/ceil.c#L3-L8

Could this be a mistake?

**Comment by kraj** [comment]
I dont think its a mistake. its defined in `include/float.h`

**Comment by colluca** [comment]
I see, thanks for your feedback :)
